import { Container, Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import './globals.css';
import './theme-config.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '../components/shared/Navbar';
import NextAuthProvider from './auth/Provider';


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={inter.variable}>
        {/* <Theme appearance="light" accentColor="violet" grayColor="slate" radius="full"></Theme> */}
        <NextAuthProvider>
          <Theme accentColor="violet" grayColor="slate" radius="medium">
            <Navbar />
            <main className='mx-auto py-8 px-4'>
              <Container>
                {children}
              </Container>
            </main>
          </Theme>
        </NextAuthProvider>
      </body>
    </html>
  )
}
